# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MoviesApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'RxSwift', '6.2.0'
  pod 'RxCocoa', '6.2.0'
  pod 'Swinject'
  pod 'Moya', '~> 15.0'

  target 'MoviesAppTests' do
    inherit! :search_paths
    pod 'RxBlocking', '6.2.0'
    pod 'RxTest', '6.2.0'
  end

  target 'MoviesAppUITests' do
    # Pods for testing
  end

end
