# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MoviesApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'Swinject'
  pod 'Moya/Combine', '~> 15.0'

  target 'MoviesAppTests' do
    inherit! :search_paths
  end

  target 'MoviesAppUITests' do
    # Pods for testing
  end

end
